services:
  - type: web
    name: telegram-bot-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: BOT_TOKEN
        fromSecret: true
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: telegram-bot-web
          property: url
    plan: free